### ISSUE TITLE
Error regarding rake when trying to install from sources

### ISSUE THREAD

**Issue by tybook** [Learnosity/vagrant-nfs_guest#55]
I was trying to follow the instructions in README.md  to build from sources and got an error like
```
ty:~/code/vagrant-nfs_guest$ bundle exec rake build
bundler: failed to load command: rake (/usr/local/bin/rake)
Gem::Exception: can't find executable rake for gem rake. rake is not currently included in the bundle, perhaps you meant to add it to your Gemfile?
  /Library/Ruby/Gems/2.3.0/gems/bundler-1.16.4/lib/bundler/rubygems_integration.rb:462:in `block in replace_bin_path'
  /Library/Ruby/Gems/2.3.0/gems/bundler-1.16.4/lib/bundler/rubygems_integration.rb:493:in `block in replace_bin_path'
  /usr/local/bin/rake:22:in `<top (required)>'
```

I had to add `gem 'rake'` to the Gemfile for it to start working.

**Comment by alangarf** [comment]
Fixed. Thanks.
